### ISSUE TITLE
Support for app extension

### ISSUE THREAD

**Issue by aliakhtar-hu** [checkout/frames-ios#404]
**Problem**
Currently, we are working to pay using Rich notification, for that, we need Frames SDK in the extension, but we are getting `'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.` 

FileName = `UIResponderExtensions.swift`

**Solution**
The solution is to add a condition for App Extension like https://github.com/SVProgressHUD/SVProgressHUD/issues/390
https://github.com/CocoaPods/CocoaPods/issues/5373#issuecomment-220486539

**Comment by aliakhtar-hu** [comment]
From Rich Notification we will add an apple pay payment for that apple pay tokenization we need frames SDK

**Comment by aliakhtar-hu** [comment]
hi @deepesh-vasthimal-cko any update on this ?

**Comment by deepesh-vasthimal-cko** [comment]
Hi @aliakhtar-hu We are currently investigating this. Can you please help what are the steps to reproduce the issue?

**Comment by aliakhtar-hu** [comment]
**Steps to Reproduce** 
- Create App Extension 
- In podfile for this extension target add
```
target 'MyExtension' do
  pod 'Frames', '3.5.2'
end
```
Build the project and build will fail and this error will come `shared is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.``

**Comment by patrick-hoban-cko** [comment]
Hi @aliakhtar-hu, thanks for raising this issue!

Supporting a payment UI via an app extension isn't a feature we have planned in our roadmap right now, mostly because we're unsure of some of the compliance and security implications of supporting this functionality.

Given it's quite a greenfield feature for us, we'd need to do a broader assessment of the impact of adding this to our SDKs. If we have anymore information we require from you, we'll reach back out. 

Hence, we don't currently have a timeline on when we could support this, but it's something we'd take into account for the long term. 

Best,

Patrick

**Comment by aliakhtar-hu** [comment]
hi @patrick-hoban-cko Maybe you misunderstood the problem 

I will make the problem short, we just want frames SDK to be built successfully in-app extension, We have our own payment UI, and we need to use some non-UI method like tokenization with this SDK but we are unable to compile SDK in the extension
